[project]
name = "laiers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "firebase-admin>=6.9.0",
    "google-adk>=1.2.1",
    "python-fasthtml>=0.12.19",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pytest>=8.4.0",
]
